#!/usr/bin/python3
import sys
import time


file = open(r"i.txt", "r")
a = file.readlines()
s = time.time()
for i in range(0, len(a)):
    a[i] = int(a[i])
    for k in range(2, int(a[i] / 2) + 1):
        if a[i] % k == 0:
            b = k
            c = int(a[i] / k)
            print("{:d}={:d}*{:d}".format(a[i], c, b))
            break
    if time.time() - s > 5:
        exit("out of the time")
