#!/usr/bin/python3
import sys
import time

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    exit()
try:    
    file = open(sys.argv[1], "r")
    a = file.readlines()
    s = time.time()
    for i in range(0, len(a)):
        a[i] = int(a[i])
        for k in range(2, int(a[i] / 2) + 1):
            if a[i] % k == 0:
                b = k
                c = int(a[i] / k)
                print(f"{a[i]:d}={c:d}*{b:d}")
                break
        if time.time() - s > 5:
            exit("out of the time")
except FileNotFoundError:
    print("file did not found")
